/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ADemo {
    }
    interface ElsTodoInput {
    }
    interface ElsTodoItems {
    }
    interface ElsTodoSummary {
    }
}
declare global {
    interface HTMLADemoElement extends Components.ADemo, HTMLStencilElement {
    }
    var HTMLADemoElement: {
        prototype: HTMLADemoElement;
        new (): HTMLADemoElement;
    };
    interface HTMLElsTodoInputElement extends Components.ElsTodoInput, HTMLStencilElement {
    }
    var HTMLElsTodoInputElement: {
        prototype: HTMLElsTodoInputElement;
        new (): HTMLElsTodoInputElement;
    };
    interface HTMLElsTodoItemsElement extends Components.ElsTodoItems, HTMLStencilElement {
    }
    var HTMLElsTodoItemsElement: {
        prototype: HTMLElsTodoItemsElement;
        new (): HTMLElsTodoItemsElement;
    };
    interface HTMLElsTodoSummaryElement extends Components.ElsTodoSummary, HTMLStencilElement {
    }
    var HTMLElsTodoSummaryElement: {
        prototype: HTMLElsTodoSummaryElement;
        new (): HTMLElsTodoSummaryElement;
    };
    interface HTMLElementTagNameMap {
        "a-demo": HTMLADemoElement;
        "els-todo-input": HTMLElsTodoInputElement;
        "els-todo-items": HTMLElsTodoItemsElement;
        "els-todo-summary": HTMLElsTodoSummaryElement;
    }
}
declare namespace LocalJSX {
    interface ADemo {
    }
    interface ElsTodoInput {
    }
    interface ElsTodoItems {
    }
    interface ElsTodoSummary {
    }
    interface IntrinsicElements {
        "a-demo": ADemo;
        "els-todo-input": ElsTodoInput;
        "els-todo-items": ElsTodoItems;
        "els-todo-summary": ElsTodoSummary;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-demo": LocalJSX.ADemo & JSXBase.HTMLAttributes<HTMLADemoElement>;
            "els-todo-input": LocalJSX.ElsTodoInput & JSXBase.HTMLAttributes<HTMLElsTodoInputElement>;
            "els-todo-items": LocalJSX.ElsTodoItems & JSXBase.HTMLAttributes<HTMLElsTodoItemsElement>;
            "els-todo-summary": LocalJSX.ElsTodoSummary & JSXBase.HTMLAttributes<HTMLElsTodoSummaryElement>;
        }
    }
}
